app/urls.py
from django.urls import path

from app.views import (
    login_view, register_view, home_view, new_post_view, hometest_view,
    post_view, about_view, dev_view, contact_view, contact_result_view
)


app_name = "app"

urlpatterns = [
    path('', home_view, name="home"),
    path('login/', login_view, name="login"),
    path('register/', register_view, name="register"),
    path('new_post/', new_post_view, name="new_post"),
    path('hometest/', hometest_view, name="hometest"),
    path('post/<int:post_id>/', post_view, name="post"),
    path('about/', about_view, name="about"),
    path('dev/', dev_view, name="dev"),
    path('contact/', contact_view, name="contact"),
    path('contact_result', contact_result_view, name="contact_result")
]

src/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app'))
]

app/models.py
from django.db import models

# Create your models here.

app/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True)

app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from django.urls import reverse

from .forms import LoginForm


# Create your views here.
def login_view(request):
    form = LoginForm()

    if request.method == "POST":
        form = LoginForm(request.POST)

        if form.is_valid():
            user = authenticate(
                username=request.POST["username"],
                password=request.POST["password"]
            )

            if user is not None:
                return redirect(reverse("app:home"))

    return render(request, 'login.html', context={"form": form})


def register_view(request):
    return render(request, 'register.html')


def home_view(request):
    return render(request, 'home.html')


def hometest_view(request):
    return render(request, 'hometest.html')


def new_post_view(request):
    return render(request, 'post.html')


def post_view(request, post_id):
    posts = {
        1: {
            "user": "Arthur",
            "content": "to deixando de assistir one piece p fazer seu "
                       "trabalho me da 10 pfvr ;-;",
            "img": "profiledaniel.jpeg"
        },
        2: {
            "user": "BolsonaroEGirl",
            "content": "gente só eu que acho lula muito bonito? s2",
            "img": "bolsonaroegrilo.jpg"
        }
    }

    post = posts[post_id]

    return render(request, template_name="see_post.html", context={"post": post})


def about_view(request):
    return render(request, template_name="about.html")


def dev_view(request):
    return render(request, template_name="dev.html")


def contact_view(request):
    return render(request, template_name="contact.html")


def contact_result_view(request):
    return render(
        request,
        template_name="contact_result.html",
        context={"form": request.POST}
    )

app/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Sobre {% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/about.css' %}" >
{% endblock css %}

{% block content %}
<div class="content">
  <h1>Sobre TheSlap</h1>

  <p>
    <b>TheSlap.com</b> é uma rede social fictícia que aparece
    no programa de tv amaericado Victorious, ou <b>Brilhante Victória</b>, como
    ficou conhecido aqui no Brasil. Neste sistema os alunos do colégio Hollywood
    Arts compartilham seus sentimentos e suas vidas, assim como as demais redes
    sociais da vida real.
  </p>
  <p>
    Fizemos este site em homenagem ao programa que tanto nos fez rir e que
    divertiu nossas vidas de adolescentes problemáticos que não pensavam em nada
    mais que One Direction, Green Day e como chamar atenção dos pais e das
    garotas do IntEd.
  </p>
</div>
{% endblock %}

app/templates/base.html
{% load static %}

<!doctype html>
<html lang="pt-br" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>TheSlap | {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}" >
    {% block css %}{% endblock css %}
</head>
<body>
<div class="logo"></div>
{% block content %}{% endblock content %}
</body>
</html>

app/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Contato {% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/contact.css' %}" >
{% endblock css %}

{% block content %}
<div class="content">
    <h4>Envie-nos um email!</h4>
    <form action="{% url 'app:contact_result' %}" method="POST">{% csrf_token %}
      <input type="email" name="email" placeholder="Email" required>
      <div class="input-group">
        <input type="text" name="first_name" placeholder="Nome" required>
        <input type="text" name="last_name" placeholder="Sobrenome" required>
      </div>
      <textarea name="content" cols="30" rows="10" placeholder="Mensagem">
      </textarea>
      <button type="submit">Enviar</button>
    </form>
</div>
{% endblock %}

app/templates/contact_result.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Contato {% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/contact.css' %}" >
{% endblock css %}

{% block content %}
<div class="content">
  <h4>Vai caralho!</h4>
  <p>
    Tamo junto demais meu aliado,
    <b>{{ form.first_name }} {{ form.last_name }}</b>,
    teu salve é foda demais pra turma daqui! Espera um minutinho que um dos
    truta da equipe vai te responder, valeu? Satisfação monstra, meu querido.
  </p>
  <p>
    Atenciosamente, Thiago 'pose de quebrada' Ventura
  </p>
</div>
{% endblock %}

app/templates/dev.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Contato {% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/dev.css' %}" >
{% endblock css %}

{% block content %}
<div class="content">
  <h1>Desenvolvedores</h1>

  <div>
    <h4>Daniel</h4>
    <a href="https://github.com/SabbathCode" target="_blank">@SabbathCode</a>
    <p>
      Daniboy, como gosta de ser chamado, é um programador indie, alternativo
      e underground apaixonado por Queen e seu legado. Não confundir com a
      Queen Elizabeth, essa aí ele não ama não.
    </p>
  </div>
  <div>
    <h4>Felipe</h4>
    <a href="https://github.com/felipe-dna" target="_blank">@felipedna</a>
    <p>
      Felipe dos dna, conhecido mundialmente como defensor do Python, ama
      Python, só fala em Python, e... programa em Python, veste Python e anda
      Python e todo Python, Python, Python, Python...
    </p>
  </div>
</div>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home {% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/home_style.css' %}" >
{% endblock css %}

{% block content %}
<form class="form" action="">
    <div class="card" >
        <div class="card_itens" >
            <a class="post_feed_01" href="{% url 'app:post' 1 %}">
                <h1>Artur</h1>
                <label>to deixando de assistir one piece p fazer seu trabalho me da 10 pfvr ;-;</label><br>
                <button class="slapar"></button>
                <button class="profilepic"></button>
            </a>

            <a class="post_feed_02" href="{% url 'app:post' 2 %}">
                <h1>BolsonaroEGirl</h1>
                <label>gente só eu que acho lula muito bonito? s2</label><br>
                <button class="slapar"></button>
                <button class="profilepic"></button>
            </a>

            </div><div class="card_profile"/></div></div>
        </div>
    </div>
</form>
{% endblock content %}

app/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Login {% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/login_style.css' %}" />
{% endblock css %}

{% block content %}
<form method="POST">{% csrf_token %}
    <div class="card">
        <div class="card_itens">
            <div class="input-group">
                <label for="user">User: </label>
                <input id="user"
                       name="username"
                       placeholder="Nome de usuário"
                       required
                >
            </div>
            <div class="input-group">
                <label for="password">Pwrd: </label>
                <input id="password"
                       type="password"
                       name="password"
                       placeholder="Password"
                       required
                >
            </div>

            <a href="{% url 'app:register' %}"
               id="btn_register"
               class="register_button"
            >
                Come Together
            </a>
            <button id="btn_login"
                    class="login_button"
                    type="submit"
            >
                Login
            </button>
        </div>
        <div class="card_profile"/></div>
    </div>
</form>
{% endblock content %}

app/templates/post.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Criar Post {% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/post_style.css' %}" >
{% endblock css %}

{% block content %}
<form class="form" action="">
    <div class="card">
        <div class="card_itens">
            <label id="labeluser">artur:</label>
            <input id="inputpost" name="User" placeholder="digite seu post">
                <select id="button">
                    <option value="0">feeling:</option>
                    <option value="1">happy</option>
                    <option value="2">more happy</option>
                    <option value="2">frustated</option>
                </select>
                </button>
        </div>
        <div class="card_profile"/>
        </div>
        <div>
            <a href="{% url 'app:home' %}" id="bttnpost">Postar</a>
        </div>
    </div>
</form>
{% endblock content %}

app/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Registro {% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/register_style.css' %}" >
{% endblock css %}

{% block content %}
<form class="form" method="POST">{% csrf_token %}
    <div class="card">
        <div class="card_itens">
            <label id="labeluser">Username: </label>
            <input id="inputuser" name="User" placeholder="Username" required />
            <label id="labelpwd">Password:</label>
            <input id="inputpwd" type="text" name="Psswd" placeholder="Password" required />
            <button id="bttnlogin" class="register_button" type="submit">register</button>
        </div>
            <div class="card_profile"/>
        </div>
    </div>
</form>
{% endblock content %}

app/templates/see_post.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Registro {% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/see_post.css' %}" >
{% endblock css %}

{% block content %}
<div class="card" >
    <div class="card_itens" >
        <div class="post_feed_01">
            <h1>{{ post.user }}</h1>
            <label>{{ post.content }}</label><br>
            <button class="slapar"></button>
            <img class="profilepic" src="../static/media/{{ post.img }}" />
        </div>

        </div><div class="card_profile" ></div></div>
    </div>
</div>
{% endblock %}